# Site settings
title: GBIF docs
email: informatics@gbif.org
description: > # this means to ignore newlines until "baseurl:"
  Write a description for the documentation site here. You can edit this
  line in _config.yml. It will appear in the document head meta (for
  Google search results).
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: gbif
facebook_username:  gbif

# Build settings
markdown: kramdown

paginate: 3
paginate_path: "news/page:num"

exclude: ["/theme-examples", "/**/README.md"]

plugins:
  - jekyll-toc
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-archives


permalink: /:year/:month/:day/:title.html

toc:
  min_level: 1 # default: 1
  max_level: 2 # default: 6

jekyll-archives:
  enabled: all
  layout: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/:name'
    tag: '/tag/:name/'
    category: '/category/:name/'

col:
  defaultImageUrl: /images/default-bg.jpg
  defaultImageCaption: "[A description](https://www.some.org/where) would go here ([CC BY-NC 4.0](http://creativecommons.org/licenses/by-nc/4.0/))"